name: Test Ptoject
on:
  push:
    tags:
      - v*
      
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16.4
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.4
    
    - name: Check out code into the Go modele directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run:  go get -v -t -d ./...
      
    - name: Test code
      run: go test -v .
